---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: kube-system
data:
  custom_conf.yml: |
    http:
      routers:
        api:
          rule: Host(`localhost`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
          entryPoints:
            - web
          service: api@internal
          middlewares:
            - auth
      middlewares:
        auth:
          basicAuth:
            users:
              - "demo:$apr1$O0CFtX8G$imfYkd3DwzUZPG3nmojco0"
